repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.7.0'
    hooks:
      # run linter
      - id: ruff
        args: ["--fix", "--show-fixes"]

      # run formatter
      - id: ruff-format
